USE QLITHONGTINHETHONGSIEUTHI
GO

CREATE PROCEDURE sp_ThongKeSanPhamDaBanTheoNgay
    @Ngay DATE
AS
BEGIN
    BEGIN TRANSACTION;
    SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

    SELECT CTDH.MA_SANPHAM, 
           SUM(CTDH.SOLUONG) AS TongSoLuongBan, 
           COUNT(DISTINCT DH.MA_DONHANG) AS SoLuongKhachHang,
           SUM(CTDH.SOLUONG * CTDH.GIABAN) AS TongDoanhThu
    INTO #ThongKeSanPham
    FROM CHITIET_DONHANG AS CTDH
    JOIN DONHANG AS DH ON CTDH.MA_DONHANG = DH.MA_DONHANG
    WHERE DH.NGAYTAO = @Ngay
    GROUP BY CTDH.MA_SANPHAM
	ORDER BY TongSoLuongBan DESC;

    INSERT INTO THONGKE_SANPHAM (THOIGIAN_THONGKE, MA_SANPHAM, SOLUONG_SANPHAM, SOLUONG_KHACHHANG_MUASANPHAM, TONG_DOANHTHU_SANPHAM)
    SELECT @Ngay, MA_SANPHAM, TongSoLuongBan, SoLuongKhachHang, TongDoanhThu
    FROM #ThongKeSanPham
    WITH (TABLOCK);

    DROP TABLE #ThongKeSanPham;

    COMMIT TRANSACTION;
END;
GO

CREATE PROCEDURE sp_ThongKeDoanhSoTheoNgay
    @Ngay DATE
AS
BEGIN
    BEGIN TRANSACTION;
    SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

    SELECT SUM(TONGGIATRI) AS TongDoanhThu,
		   COUNT(DISTINCT MA_DONHANG) AS SoLuongKhachHang
	INTO #ThongKeDoanhSo
    FROM DONHANG
    WHERE NGAYTAO = @Ngay;

    INSERT INTO THONGKE_DOANHSO (THOIGIAN_THONGKE, TONG_DOANHTHU, TONG_KHACHHANG)
	SELECT @Ngay, TongDoanhThu, SoLuongKhachHang
    FROM #ThongKeDoanhSo
    WITH (TABLOCK);

    DROP TABLE #ThongKeDoanhSo;

    COMMIT TRANSACTION;
END;
GO
