USE master
GO
IF DB_ID('QLITHONGTINHETHONGSIEUTHI') IS NOT NULL
	DROP DATABASE QLITHONGTINHETHONGSIEUTHI
GO

CREATE DATABASE QLITHONGTINHETHONGSIEUTHI;
GO

USE QLITHONGTINHETHONGSIEUTHI
GO

--Phân hạng khách hàng
CREATE TABLE PHANHANG
(
	MA_PHANHANG INT,
	TEN_PHANHANG CHAR(10),
	TIENTOITHIEU FLOAT,
	GIATRI_PHIEUTANG FLOAT

	CONSTRAINT PK_PHANHANG
	PRIMARY KEY (MA_PHANHANG)
)


--Nhà sản xuất
CREATE TABLE NHASANXUAT
(
	MA_NHASANXUAT CHAR(10),
	TEN_NHASANXUAT NVARCHAR(50),
	DIACHI NVARCHAR(100),
	SDT CHAR(10),

	CONSTRAINT PK_NHASANXUAT
	PRIMARY KEY (MA_NHASANXUAT)
)

--Mục (danh mục sản phẩm)
CREATE TABLE MUC
(
	MA_MUC CHAR(10),
	TEN_MUC NVARCHAR(20),
	SOLUONG_SANPHAN INT,
	MA_MUC_CHA CHAR(10),

	CONSTRAINT PK_MUC
	PRIMARY KEY (MA_MUC)
)

--Sản phẩm
CREATE TABLE SANPHAM
(
	MA_SANPHAM CHAR(10),
	MA_MUC CHAR(10),
	MA_NHASANXUAT CHAR(10),
	TENSANPHAM NVARCHAR(50),
	GIATIEN INT,
	THONGTIN_SANPHAM NVARCHAR(100),
	NHASANXUAT NVARCHAR(50),
	NGAYSANXUAT DATE,
	HANSUDUNG DATE,
	SOLUONG_TOIDA INT,

	CONSTRAINT PK_SANPHAM
	PRIMARY KEY (MA_SANPHAM),

	--FOREIGN KEY tới MUC
	CONSTRAINT FK_SANPHAM_MUC
	FOREIGN KEY (MA_MUC)
	REFERENCES MUC,

	--FOREIGN KEY tới NHASANXUAT
	CONSTRAINT FK_SANPHAM_NHASANXUAT
	FOREIGN KEY (MA_NHASANXUAT)
	REFERENCES NHASANXUAT
)

--Khách hàng
CREATE TABLE KHACHHANG
(
	MA_KHACHHANG CHAR(10),
	SDT CHAR(10),
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	NGAYDANGKY DATE,
	MA_PHANHANG INT,

	CONSTRAINT PK_KHACHHANG
	PRIMARY KEY (MA_KHACHHANG),

	--FOREIGN KEY tới PHANHANG
	CONSTRAINT FK_KHACHHANG_PHANHANG
	FOREIGN KEY(MA_PHANHANG) 
	REFERENCES PHANHANG
)

--Danh sách đơn đặt hàng đến nhà sản xuất để nhập hàng
CREATE TABLE DONDATHANG
(
	MA_DONDATHANG CHAR(10),
	MA_NHASANXUAT CHAR(10),
	NGAYDATHANG DATE,
	TINHTRANG CHAR(20),

	CONSTRAINT PK_DONDATHANG
	PRIMARY KEY (MA_DONDATHANG),

	--FOREIGN KEY tới NHASANXUAT
	CONSTRAINT FK_DONDATHANG_NHASANXUAT
	FOREIGN KEY(MA_NHASANXUAT)
	REFERENCES NHASANXUAT
)

--Chi tiết đơn đặt hàng đến nhà sản xuất để nhập hàng
CREATE TABLE CHITIET_DONDATHANG
(
	MA_DONDATHANG CHAR(10),
	MA_SANPHAM CHAR(10),
	SOLUONG_DATHANG INT,
	
	CONSTRAINT PK_CHITIET_DONDATHANG
	PRIMARY KEY (MA_DONDATHANG, MA_SANPHAM),

	--FOREIGN KEY tới DONDATHANG
	CONSTRAINT FK_CHITIET_DONDATHANG_DONDATHANG
	FOREIGN KEY(MA_DONDATHANG)
	REFERENCES DONDATHANG,

	--FOREIGN KEY tới SANPHAM
	CONSTRAINT FK_CHITIET_DONDATHANG_SANPHAM
	FOREIGN KEY(MA_SANPHAM)
	REFERENCES SANPHAM
)

--Nhập hàng 
CREATE TABLE NHAPHANG
(
	MA_NHAPHANG CHAR(10),
	NGAY_NHAPHANG CHAR(10),
	
	CONSTRAINT PK_NHAPHANG
	PRIMARY KEY (MA_NHAPHANG)
)

--Chi tiết nhập hàng
CREATE TABLE CHITIET_NHAPHANG
(
	MA_NHAPHANG CHAR(10),
	MA_SANPHAM CHAR(10),
	SOLUONG_NHAPHANG INT


	CONSTRAINT PK_CHITIET_NHAPHANG
	PRIMARY KEY (MA_NHAPHANG, MA_SANPHAM)

	--FOREIGN KEY tới NHAPHANG
	CONSTRAINT FK_CHITIET_NHAPHANG_NHAPHANG
	FOREIGN KEY(MA_NHAPHANG)
	REFERENCES NHAPHANG,

	--FOREIGN KEY tới SANPHAM
	CONSTRAINT FK_CHITIET_NHAPHANG_SANPHAM
	FOREIGN KEY(MA_SANPHAM)
	REFERENCES SANPHAM
)


--Chương trình khuyến mãi cho từng phân hạng khách hàng
CREATE TABLE CHUONGTRINH_KHUYENMAI
(
	MA_CTKM CHAR(10) ,
	TEN_CTKM NVARCHAR(50),
	LOAI_CTKM CHAR(20),
	MA_KHACHHANG CHAR(10),
	THOIGIANBATDAU DATE,
	THOIGIANKETTHUC DATE,


	CONSTRAINT PK_CHUONGTRINH_KHUYENMAI
	PRIMARY KEY (MA_CTKM),

	--FOREIGN KEY tới PHANHANG
	CONSTRAINT FK_CHUONGTRINH_KHUYENMAI_KHACHHANG
	FOREIGN KEY(MA_KHACHHANG)
	REFERENCES KHACHHANG
)

--Sản phẩm khuyến mãi cho Flash Sale và Member Sale
CREATE TABLE SANPHAM_KHUYENMAI
(
	MA_SANPHAM CHAR(10),
	MA_CHUONGTRINH CHAR(10),
	MUC_GIAMGIA FLOAT,
	SOLUONG_SANPHAM_KHUYENMAI INT,
	TINHTRANG  CHAR(10),

	CONSTRAINT PK_SANPHAM_KHUYENMAI
	PRIMARY KEY (MA_SANPHAM, MA_CHUONGTRINH),

	--FOREIGN KEY tới SANPHAM
	CONSTRAINT FK_SANPHAM_KHUYENMAI_SANPHAM
	FOREIGN KEY(MA_SANPHAM)
	REFERENCES SANPHAM,

	--FOREIGN KEY tới CHUONGTRINH_KHUYENMAI
	CONSTRAINT FK_SANPHAM_KHUYENMAI_CHUONGTRINH_KHUYENMAI
	FOREIGN KEY(MA_CHUONGTRINH)
	REFERENCES CHUONGTRINH_KHUYENMAI
)


--Sản phẩm khuyến mãi cho Combo Sale
CREATE TABLE SANPHAM_KHUYENMAI_COMBO
(
	
	MA_SANPHAM_1 CHAR(10),
	MA_SANPHAM_2 CHAR(10),
	MA_CHUONGTRINH CHAR(10),
	MUC_GIAMGIA FLOAT,
	SOLUONG_SANPHAM_KHUYENMAI INT,
	TINHTRANG  CHAR(10),

	CONSTRAINT PK_SANPHAM_KHUYENMAI_COMBO
	PRIMARY KEY (MA_SANPHAM_1, MA_SANPHAM_2, MA_CHUONGTRINH)
)

--Phiếu mua hàng
CREATE TABLE PHIEUMUAHANG
(
	MA_PHIEUMUAHANG CHAR(10),
	GIATRI_PHIEUMUAHANG INT,
	NGAYAPDUNG DATE,
	NGAYHETHAN DATE,
	TRANGTHAI_PHIEUMUAHANG NVARCHAR(20),

	CONSTRAINT PK_PHIEUMUAHANG
	PRIMARY KEY (MA_PHIEUMUAHANG)
)

--Hoá đơn mua hàng
CREATE TABLE DONHANG
(
	MA_DONHANG CHAR(10),
	MA_KHACHHANG CHAR(10),
	MA_PHIEUMUAHANG CHAR(10) ,
	THOIGIANTAO_DONHANG DATETIME,
	TONGGIATRI INT,
	HINHTHUC_MUAHANG CHAR(7),
	TRANGTHAI_DONHANG NVARCHAR(20),
	NGAYTAO DATETIME,
	PHUONGTHUC_THANHTOAN CHAR(7),
	TRANGTHAI_THANHTOAN CHAR(10)

	CONSTRAINT PK_DONHANG
	PRIMARY KEY (MA_DONHANG)

	--FOREIGN KEY tới KHACHHANG
	CONSTRAINT FK_DONHANG_KHACHHANG
	FOREIGN KEY(MA_KHACHHANG)
	REFERENCES KHACHHANG,

	--FOREIGN KEY tới PHIEUMUAHANG
	CONSTRAINT FK_DONHANG_PHIEUMUAHANG
	FOREIGN KEY(MA_PHIEUMUAHANG)
	REFERENCES PHIEUMUAHANG
)


--Chi tiết hoá đơn mua hàng
CREATE TABLE CHITIET_DONHANG
(
	MA_CTDH CHAR(10),
	MA_DONHANG CHAR(10),
	MA_SANPHAM CHAR(10),
	SOLUONG INT,
	GIABAN INT,
	GIATRIKHUYENMAI INT,

	CONSTRAINT PK_CHITIET_DONHANG
	PRIMARY KEY (MA_CTDH),

	--FOREIGN KEY tới DONHANG
	CONSTRAINT FK_CHITIET_DONHANG_DONHANG
	FOREIGN KEY(MA_DONHANG)
	REFERENCES DONHANG,

	--FOREIGN KEY tới SANPHAM
	CONSTRAINT FK_CHITIETDONHANG_SANPHAM
	FOREIGN KEY(MA_SANPHAM)
	REFERENCES SANPHAM
)

--Phiếu sinh nhật cho khách hàng theo phân hạng
CREATE TABLE PHIEUSINHNHAT
(
	MA_KHACHHANG CHAR(10),
	NGAYPHATHANH DATE,
	TRANGTHAI_PHIEUSINHNHAT NVARCHAR(20),
	GIATRIPHIEU INT

	CONSTRAINT PK_PHIEUSINHHAT
	PRIMARY KEY (MA_KHACHHANG, NGAYPHATHANH),

	--FOREIGN KEY tới KHACHHANG
	CONSTRAINT FK_PHIEUSINHNHAT_KHACHHANG
	FOREIGN KEY(MA_KHACHHANG)
	REFERENCES KHACHHANG
)

--Kho hàng lưu trữ số lượng còn lại của sản phẩm và số lượng tối đa
CREATE TABLE KHOHANG
(
	MA_KHOHANG CHAR(10),
	MA_SANPHAM CHAR(10),
	SOLUONG_CONLAI INT,
	SOLUONG_TOIDA INT,

	CONSTRAINT PK_KHOHANG
	PRIMARY KEY (MA_KHOHANG)
)

--Thống kê doanh thu hàng ngày
CREATE TABLE THONGKE_DONHANG
(
	MA_THONGKE_DONHANG CHAR(10),
	THOIGIAN_THONGKE DATETIME,
	SOLUONG_DONHANG INT, 
	TONG_DOANHTHU DEC(10, 3),
	TONG_KHACHHANG INT,
	
	CONSTRAINT PK_THONGKE_DONHANG
	PRIMARY KEY(MA_THONGKE_DONHANG)
)

--Thống kê sản phẩm bán ra hàng ngày
CREATE TABLE THONGKE_SANPHAM
(
	MA_THONGKE_SANPHAM CHAR(10),
	MA_SANPHAM CHAR(10),
	SOLUONG_SANPHAM INT,
	SOLUONG_KHACHHANG_MUASANPHAM INT,
	THOIGIAN_THONGKE DATETIME
)

--Chi tiết thống kê kho hàng ngày phục vụ cho việc cập nhật số lượng tồn kho
CREATE TABLE CHITIET_THONGKE_KHO_HANGNGAY
(
	THOIGIAN_THONGKE DATE,
	MA_SANPHAM CHAR(10),
	SOLUONG_TONKHO INT, --cho update
	SOLUONG_CANDAT INT,
	SOLUONG_CONNO INT,

	CONSTRAINT PK_CHITIET_THONGKET_KHO_HANGNGAY
	PRIMARY KEY (THOIGIAN_THONGKE, MA_SANPHAM),

	--FOREIGN KEY tới SANPHAM
	CONSTRAINT FK_CHITIET_THONGKE_KHO_HANGNGAY_SANPHAM
	FOREIGN KEY(MA_SANPHAM)
	REFERENCES SANPHAM
)

--Integrity constraint (trigger)
